package cmdb

type ATTRIBUTE_VALUE_TYPE string

const (
	ATTRIBUTE_VALUE_TYPE_TEXT    ATTRIBUTE_VALUE_TYPE = "value_text"
	ATTRIBUTE_VALUE_TYPE_DATE    ATTRIBUTE_VALUE_TYPE = "value_date"
	ATTRIBUTE_VALUE_TYPE_DEFAULT ATTRIBUTE_VALUE_TYPE = "value_default"
	ATTRIBUTE_VALUE_TYPE_CI      ATTRIBUTE_VALUE_TYPE = "value_ci"
)
