package cmdb

type CI_RELATION_DIRECTION string

const (
	CI_RELATION_DIRECTION_ALL             CI_RELATION_DIRECTION = "all"
	CI_RELATION_DIRECTION_DIRECTED_FROM   CI_RELATION_DIRECTION = "directed_from"
	CI_RELATION_DIRECTION_DIRECTED_TO     CI_RELATION_DIRECTION = "directed_to"
	CI_RELATION_DIRECTION_BIDIRECTIONAL   CI_RELATION_DIRECTION = "bidirectional"
	CI_RELATION_DIRECTION_OMNIDIRECTIONAL CI_RELATION_DIRECTION = "omnidirectional"
)
