package infocmdb

import (
	"testing"

	utilTesting "github.com/infonova/infocmdb-sdk-go/util/testing"
)

func TestInfoCMDB_CiListByCiTypeID(t *testing.T) {
	ut := utilTesting.New()
	configFile := utilTesting.BuildValidConfig(ut.GetUrl())
	ut.AddMocking(utilTesting.Mocking{
		RequestString: "GET##/apiV2/ci/index?ciTypeId=12##",
		ReturnString:  `{
    "success": true,
    "message": "success",
    "data": {
        "data": {
            "ciList": [
                {
                    "id": "436",
                    "ci_project_ids": "831,832",
                    "emp_ad_username": "cornelia.blank",
                    "emp_ad_usernameID": "3362",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "3360",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Linux Mint",
                    "emp_client_linux_distroID": "3363",
                    "emp_staff_number": "91651",
                    "emp_staff_numberID": "3356",
                    "emp_firstname": "Cornelia",
                    "emp_firstnameID": "3357",
                    "emp_lastname": "Blank",
                    "emp_lastnameID": "3358",
                    "emp_email_address": "cornelia.blank@example.com",
                    "emp_email_addressID": "3359",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "427",
                    "ci_project_ids": "813,814",
                    "emp_ad_username": "kati.jacob",
                    "emp_ad_usernameID": "3290",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "3288",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Manjaro",
                    "emp_client_linux_distroID": "3291",
                    "emp_staff_number": "14058",
                    "emp_staff_numberID": "3284",
                    "emp_firstname": "Kati",
                    "emp_firstnameID": "3285",
                    "emp_lastname": "Jacob",
                    "emp_lastnameID": "3286",
                    "emp_email_address": "kati.jacob@example.com",
                    "emp_email_addressID": "3287",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "424",
                    "ci_project_ids": "807,808",
                    "emp_ad_username": "martha.sonntag",
                    "emp_ad_usernameID": "3266",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "3264",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Ubuntu",
                    "emp_client_linux_distroID": "3267",
                    "emp_staff_number": "88813",
                    "emp_staff_numberID": "3260",
                    "emp_firstname": "Martha",
                    "emp_firstnameID": "3261",
                    "emp_lastname": "Sonntag",
                    "emp_lastnameID": "3262",
                    "emp_email_address": "martha.sonntag@example.com",
                    "emp_email_addressID": "3263",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "422",
                    "ci_project_ids": "803,804",
                    "emp_ad_username": "annett.stoll",
                    "emp_ad_usernameID": "3250",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "3248",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Debian",
                    "emp_client_linux_distroID": "3251",
                    "emp_staff_number": "31400",
                    "emp_staff_numberID": "3244",
                    "emp_firstname": "Annett",
                    "emp_firstnameID": "3245",
                    "emp_lastname": "Stoll",
                    "emp_lastnameID": "3246",
                    "emp_email_address": "annett.stoll@example.com",
                    "emp_email_addressID": "3247",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "418",
                    "ci_project_ids": "795,796",
                    "emp_ad_username": "tatjana.erdmann",
                    "emp_ad_usernameID": "3218",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "3216",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Debian",
                    "emp_client_linux_distroID": "3219",
                    "emp_staff_number": "73240",
                    "emp_staff_numberID": "3212",
                    "emp_firstname": "Tatjana",
                    "emp_firstnameID": "3213",
                    "emp_lastname": "Erdmann",
                    "emp_lastnameID": "3214",
                    "emp_email_address": "tatjana.erdmann@example.com",
                    "emp_email_addressID": "3215",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "414",
                    "ci_project_ids": "787,788",
                    "emp_ad_username": "stanislaw.voigt",
                    "emp_ad_usernameID": "3186",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "3184",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Ubuntu",
                    "emp_client_linux_distroID": "3187",
                    "emp_staff_number": "12446",
                    "emp_staff_numberID": "3180",
                    "emp_firstname": "Stanislaw",
                    "emp_firstnameID": "3181",
                    "emp_lastname": "Voigt",
                    "emp_lastnameID": "3182",
                    "emp_email_address": "stanislaw.voigt@example.com",
                    "emp_email_addressID": "3183",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "402",
                    "ci_project_ids": "763,764",
                    "emp_ad_username": "yusuf.binder",
                    "emp_ad_usernameID": "3090",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "3088",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Debian",
                    "emp_client_linux_distroID": "3091",
                    "emp_staff_number": "28220",
                    "emp_staff_numberID": "3084",
                    "emp_firstname": "Yusuf",
                    "emp_firstnameID": "3085",
                    "emp_lastname": "Binder",
                    "emp_lastnameID": "3086",
                    "emp_email_address": "yusuf.binder@example.com",
                    "emp_email_addressID": "3087",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "398",
                    "ci_project_ids": "755,756",
                    "emp_ad_username": "carsten.witt",
                    "emp_ad_usernameID": "3058",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "3056",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Manjaro",
                    "emp_client_linux_distroID": "3059",
                    "emp_staff_number": "80702",
                    "emp_staff_numberID": "3052",
                    "emp_firstname": "Carsten",
                    "emp_firstnameID": "3053",
                    "emp_lastname": "Witt",
                    "emp_lastnameID": "3054",
                    "emp_email_address": "carsten.witt@example.com",
                    "emp_email_addressID": "3055",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "392",
                    "ci_project_ids": "743,744",
                    "emp_ad_username": "henriette.grimm",
                    "emp_ad_usernameID": "3010",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "3008",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Manjaro",
                    "emp_client_linux_distroID": "3011",
                    "emp_staff_number": "45798",
                    "emp_staff_numberID": "3004",
                    "emp_firstname": "Henriette",
                    "emp_firstnameID": "3005",
                    "emp_lastname": "Grimm",
                    "emp_lastnameID": "3006",
                    "emp_email_address": "henriette.grimm@example.com",
                    "emp_email_addressID": "3007",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "372",
                    "ci_project_ids": "703,704",
                    "emp_ad_username": "arno.schr&ouml;der",
                    "emp_ad_usernameID": "2850",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "2848",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Debian",
                    "emp_client_linux_distroID": "2851",
                    "emp_staff_number": "68993",
                    "emp_staff_numberID": "2844",
                    "emp_firstname": "Arno",
                    "emp_firstnameID": "2845",
                    "emp_lastname": "Schr&ouml;der",
                    "emp_lastnameID": "2846",
                    "emp_email_address": "arno.schr&ouml;der@example.com",
                    "emp_email_addressID": "2847",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "368",
                    "ci_project_ids": "695,696",
                    "emp_ad_username": "lutz.keil",
                    "emp_ad_usernameID": "2818",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "2816",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Ubuntu",
                    "emp_client_linux_distroID": "2819",
                    "emp_staff_number": "65372",
                    "emp_staff_numberID": "2812",
                    "emp_firstname": "Lutz",
                    "emp_firstnameID": "2813",
                    "emp_lastname": "Keil",
                    "emp_lastnameID": "2814",
                    "emp_email_address": "lutz.keil@example.com",
                    "emp_email_addressID": "2815",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "360",
                    "ci_project_ids": "679,680",
                    "emp_ad_username": "susann.anders",
                    "emp_ad_usernameID": "2754",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "2752",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "ArchLinux",
                    "emp_client_linux_distroID": "2755",
                    "emp_staff_number": "60841",
                    "emp_staff_numberID": "2748",
                    "emp_firstname": "Susann",
                    "emp_firstnameID": "2749",
                    "emp_lastname": "Anders",
                    "emp_lastnameID": "2750",
                    "emp_email_address": "susann.anders@example.com",
                    "emp_email_addressID": "2751",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "356",
                    "ci_project_ids": "671,672",
                    "emp_ad_username": "marco.sch&uuml;ler",
                    "emp_ad_usernameID": "2722",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "2720",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Linux Mint",
                    "emp_client_linux_distroID": "2723",
                    "emp_staff_number": "15055",
                    "emp_staff_numberID": "2716",
                    "emp_firstname": "Marco",
                    "emp_firstnameID": "2717",
                    "emp_lastname": "Sch&uuml;ler",
                    "emp_lastnameID": "2718",
                    "emp_email_address": "marco.sch&uuml;ler@example.com",
                    "emp_email_addressID": "2719",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "353",
                    "ci_project_ids": "665,666",
                    "emp_ad_username": "metin.linke",
                    "emp_ad_usernameID": "2698",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "2696",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "ArchLinux",
                    "emp_client_linux_distroID": "2699",
                    "emp_staff_number": "97371",
                    "emp_staff_numberID": "2692",
                    "emp_firstname": "Metin",
                    "emp_firstnameID": "2693",
                    "emp_lastname": "Linke",
                    "emp_lastnameID": "2694",
                    "emp_email_address": "metin.linke@example.com",
                    "emp_email_addressID": "2695",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "351",
                    "ci_project_ids": "661,662",
                    "emp_ad_username": "nancy.schott",
                    "emp_ad_usernameID": "2682",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "2680",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Ubuntu",
                    "emp_client_linux_distroID": "2683",
                    "emp_staff_number": "84522",
                    "emp_staff_numberID": "2676",
                    "emp_firstname": "Nancy",
                    "emp_firstnameID": "2677",
                    "emp_lastname": "Schott",
                    "emp_lastnameID": "2678",
                    "emp_email_address": "nancy.schott@example.com",
                    "emp_email_addressID": "2679",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "350",
                    "ci_project_ids": "659,660",
                    "emp_ad_username": "hedi.steffens",
                    "emp_ad_usernameID": "2674",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "2672",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Manjaro",
                    "emp_client_linux_distroID": "2675",
                    "emp_staff_number": "26052",
                    "emp_staff_numberID": "2668",
                    "emp_firstname": "Hedi",
                    "emp_firstnameID": "2669",
                    "emp_lastname": "Steffens",
                    "emp_lastnameID": "2670",
                    "emp_email_address": "hedi.steffens@example.com",
                    "emp_email_addressID": "2671",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "348",
                    "ci_project_ids": "655,656",
                    "emp_ad_username": "gertraud.fritz",
                    "emp_ad_usernameID": "2658",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "2656",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Linux Mint",
                    "emp_client_linux_distroID": "2659",
                    "emp_staff_number": "1468",
                    "emp_staff_numberID": "2652",
                    "emp_firstname": "Gertraud",
                    "emp_firstnameID": "2653",
                    "emp_lastname": "Fritz",
                    "emp_lastnameID": "2654",
                    "emp_email_address": "gertraud.fritz@example.com",
                    "emp_email_addressID": "2655",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "347",
                    "ci_project_ids": "653,654",
                    "emp_ad_username": "harro.langer",
                    "emp_ad_usernameID": "2650",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "2648",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Debian",
                    "emp_client_linux_distroID": "2651",
                    "emp_staff_number": "54674",
                    "emp_staff_numberID": "2644",
                    "emp_firstname": "Harro",
                    "emp_firstnameID": "2645",
                    "emp_lastname": "Langer",
                    "emp_lastnameID": "2646",
                    "emp_email_address": "harro.langer@example.com",
                    "emp_email_addressID": "2647",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "346",
                    "ci_project_ids": "651,652",
                    "emp_ad_username": "klaus-j&uuml;rgen.meyer",
                    "emp_ad_usernameID": "2642",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "2640",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "ArchLinux",
                    "emp_client_linux_distroID": "2643",
                    "emp_staff_number": "87545",
                    "emp_staff_numberID": "2636",
                    "emp_firstname": "Klaus-J&uuml;rgen",
                    "emp_firstnameID": "2637",
                    "emp_lastname": "Meyer",
                    "emp_lastnameID": "2638",
                    "emp_email_address": "klaus-j&uuml;rgen.meyer@example.com",
                    "emp_email_addressID": "2639",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "338",
                    "ci_project_ids": "635,636",
                    "emp_ad_username": "heinz-g&uuml;nter.hammer",
                    "emp_ad_usernameID": "2578",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "2576",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Ubuntu",
                    "emp_client_linux_distroID": "2579",
                    "emp_staff_number": "87033",
                    "emp_staff_numberID": "2572",
                    "emp_firstname": "Heinz-G&uuml;nter",
                    "emp_firstnameID": "2573",
                    "emp_lastname": "Hammer",
                    "emp_lastnameID": "2574",
                    "emp_email_address": "heinz-g&uuml;nter.hammer@example.com",
                    "emp_email_addressID": "2575",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "330",
                    "ci_project_ids": "619,620",
                    "emp_ad_username": "tanja.haas",
                    "emp_ad_usernameID": "2514",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "2512",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Manjaro",
                    "emp_client_linux_distroID": "2515",
                    "emp_staff_number": "93560",
                    "emp_staff_numberID": "2508",
                    "emp_firstname": "Tanja",
                    "emp_firstnameID": "2509",
                    "emp_lastname": "Haas",
                    "emp_lastnameID": "2510",
                    "emp_email_address": "tanja.haas@example.com",
                    "emp_email_addressID": "2511",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "319",
                    "ci_project_ids": "597,598",
                    "emp_ad_username": "rosel.naumann",
                    "emp_ad_usernameID": "2426",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "2424",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Debian",
                    "emp_client_linux_distroID": "2427",
                    "emp_staff_number": "88008",
                    "emp_staff_numberID": "2420",
                    "emp_firstname": "Rosel",
                    "emp_firstnameID": "2421",
                    "emp_lastname": "Naumann",
                    "emp_lastnameID": "2422",
                    "emp_email_address": "rosel.naumann@example.com",
                    "emp_email_addressID": "2423",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "316",
                    "ci_project_ids": "591,592",
                    "emp_ad_username": "ferdinand.klose",
                    "emp_ad_usernameID": "2402",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "2400",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Ubuntu",
                    "emp_client_linux_distroID": "2403",
                    "emp_staff_number": "441",
                    "emp_staff_numberID": "2396",
                    "emp_firstname": "Ferdinand",
                    "emp_firstnameID": "2397",
                    "emp_lastname": "Klose",
                    "emp_lastnameID": "2398",
                    "emp_email_address": "ferdinand.klose@example.com",
                    "emp_email_addressID": "2399",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "315",
                    "ci_project_ids": "589,590",
                    "emp_ad_username": "mirco.paul",
                    "emp_ad_usernameID": "2394",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "2392",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Ubuntu",
                    "emp_client_linux_distroID": "2395",
                    "emp_staff_number": "40738",
                    "emp_staff_numberID": "2388",
                    "emp_firstname": "Mirco",
                    "emp_firstnameID": "2389",
                    "emp_lastname": "Paul",
                    "emp_lastnameID": "2390",
                    "emp_email_address": "mirco.paul@example.com",
                    "emp_email_addressID": "2391",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "308",
                    "ci_project_ids": "575,576",
                    "emp_ad_username": "gabriel.peters",
                    "emp_ad_usernameID": "2338",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "2336",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "ArchLinux",
                    "emp_client_linux_distroID": "2339",
                    "emp_staff_number": "21513",
                    "emp_staff_numberID": "2332",
                    "emp_firstname": "Gabriel",
                    "emp_firstnameID": "2333",
                    "emp_lastname": "Peters",
                    "emp_lastnameID": "2334",
                    "emp_email_address": "gabriel.peters@example.com",
                    "emp_email_addressID": "2335",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "300",
                    "ci_project_ids": "559,560",
                    "emp_ad_username": "wanda.mann",
                    "emp_ad_usernameID": "2274",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "2272",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Ubuntu",
                    "emp_client_linux_distroID": "2275",
                    "emp_staff_number": "26024",
                    "emp_staff_numberID": "2268",
                    "emp_firstname": "Wanda",
                    "emp_firstnameID": "2269",
                    "emp_lastname": "Mann",
                    "emp_lastnameID": "2270",
                    "emp_email_address": "wanda.mann@example.com",
                    "emp_email_addressID": "2271",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "283",
                    "ci_project_ids": "525,526",
                    "emp_ad_username": "hilmar.koch",
                    "emp_ad_usernameID": "2138",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "2136",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Linux Mint",
                    "emp_client_linux_distroID": "2139",
                    "emp_staff_number": "27854",
                    "emp_staff_numberID": "2132",
                    "emp_firstname": "Hilmar",
                    "emp_firstnameID": "2133",
                    "emp_lastname": "Koch",
                    "emp_lastnameID": "2134",
                    "emp_email_address": "hilmar.koch@example.com",
                    "emp_email_addressID": "2135",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "280",
                    "ci_project_ids": "519,520",
                    "emp_ad_username": "heidemarie.buchholz",
                    "emp_ad_usernameID": "2114",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "2112",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Ubuntu",
                    "emp_client_linux_distroID": "2115",
                    "emp_staff_number": "59788",
                    "emp_staff_numberID": "2108",
                    "emp_firstname": "Heidemarie",
                    "emp_firstnameID": "2109",
                    "emp_lastname": "Buchholz",
                    "emp_lastnameID": "2110",
                    "emp_email_address": "heidemarie.buchholz@example.com",
                    "emp_email_addressID": "2111",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "279",
                    "ci_project_ids": "517,518",
                    "emp_ad_username": "anne.unger",
                    "emp_ad_usernameID": "2106",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "2104",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Debian",
                    "emp_client_linux_distroID": "2107",
                    "emp_staff_number": "14885",
                    "emp_staff_numberID": "2100",
                    "emp_firstname": "Anne",
                    "emp_firstnameID": "2101",
                    "emp_lastname": "Unger",
                    "emp_lastnameID": "2102",
                    "emp_email_address": "anne.unger@example.com",
                    "emp_email_addressID": "2103",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "272",
                    "ci_project_ids": "503,504",
                    "emp_ad_username": "teresa.baumgartner",
                    "emp_ad_usernameID": "2050",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "2048",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Debian",
                    "emp_client_linux_distroID": "2051",
                    "emp_staff_number": "22502",
                    "emp_staff_numberID": "2044",
                    "emp_firstname": "Teresa",
                    "emp_firstnameID": "2045",
                    "emp_lastname": "Baumgartner",
                    "emp_lastnameID": "2046",
                    "emp_email_address": "teresa.baumgartner@example.com",
                    "emp_email_addressID": "2047",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "269",
                    "ci_project_ids": "497,498",
                    "emp_ad_username": "elena.reimer",
                    "emp_ad_usernameID": "2026",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "2024",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "ArchLinux",
                    "emp_client_linux_distroID": "2027",
                    "emp_staff_number": "80008",
                    "emp_staff_numberID": "2020",
                    "emp_firstname": "Elena",
                    "emp_firstnameID": "2021",
                    "emp_lastname": "Reimer",
                    "emp_lastnameID": "2022",
                    "emp_email_address": "elena.reimer@example.com",
                    "emp_email_addressID": "2023",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "262",
                    "ci_project_ids": "483,484",
                    "emp_ad_username": "mike.hummel",
                    "emp_ad_usernameID": "1970",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "1968",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Debian",
                    "emp_client_linux_distroID": "1971",
                    "emp_staff_number": "20183",
                    "emp_staff_numberID": "1964",
                    "emp_firstname": "Mike",
                    "emp_firstnameID": "1965",
                    "emp_lastname": "Hummel",
                    "emp_lastnameID": "1966",
                    "emp_email_address": "mike.hummel@example.com",
                    "emp_email_addressID": "1967",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "258",
                    "ci_project_ids": "475,476",
                    "emp_ad_username": "karl-friedrich.klaus",
                    "emp_ad_usernameID": "1938",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "1936",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "ArchLinux",
                    "emp_client_linux_distroID": "1939",
                    "emp_staff_number": "44922",
                    "emp_staff_numberID": "1932",
                    "emp_firstname": "Karl-Friedrich",
                    "emp_firstnameID": "1933",
                    "emp_lastname": "Klaus",
                    "emp_lastnameID": "1934",
                    "emp_email_address": "karl-friedrich.klaus@example.com",
                    "emp_email_addressID": "1935",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "252",
                    "ci_project_ids": "463,464",
                    "emp_ad_username": "winfried.wunderlich",
                    "emp_ad_usernameID": "1890",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "1888",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Linux Mint",
                    "emp_client_linux_distroID": "1891",
                    "emp_staff_number": "93024",
                    "emp_staff_numberID": "1884",
                    "emp_firstname": "Winfried",
                    "emp_firstnameID": "1885",
                    "emp_lastname": "Wunderlich",
                    "emp_lastnameID": "1886",
                    "emp_email_address": "winfried.wunderlich@example.com",
                    "emp_email_addressID": "1887",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "247",
                    "ci_project_ids": "453,454",
                    "emp_ad_username": "mandy.pfeifer",
                    "emp_ad_usernameID": "1850",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "1848",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "ArchLinux",
                    "emp_client_linux_distroID": "1851",
                    "emp_staff_number": "63912",
                    "emp_staff_numberID": "1844",
                    "emp_firstname": "Mandy",
                    "emp_firstnameID": "1845",
                    "emp_lastname": "Pfeifer",
                    "emp_lastnameID": "1846",
                    "emp_email_address": "mandy.pfeifer@example.com",
                    "emp_email_addressID": "1847",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "246",
                    "ci_project_ids": "451,452",
                    "emp_ad_username": "centa.bauer",
                    "emp_ad_usernameID": "1842",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "1840",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Debian",
                    "emp_client_linux_distroID": "1843",
                    "emp_staff_number": "58016",
                    "emp_staff_numberID": "1836",
                    "emp_firstname": "Centa",
                    "emp_firstnameID": "1837",
                    "emp_lastname": "Bauer",
                    "emp_lastnameID": "1838",
                    "emp_email_address": "centa.bauer@example.com",
                    "emp_email_addressID": "1839",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "245",
                    "ci_project_ids": "449,450",
                    "emp_ad_username": "ottilie.frey",
                    "emp_ad_usernameID": "1834",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "1832",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Manjaro",
                    "emp_client_linux_distroID": "1835",
                    "emp_staff_number": "88855",
                    "emp_staff_numberID": "1828",
                    "emp_firstname": "Ottilie",
                    "emp_firstnameID": "1829",
                    "emp_lastname": "Frey",
                    "emp_lastnameID": "1830",
                    "emp_email_address": "ottilie.frey@example.com",
                    "emp_email_addressID": "1831",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "244",
                    "ci_project_ids": "447,448",
                    "emp_ad_username": "horst-dieter.berg",
                    "emp_ad_usernameID": "1826",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "1824",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Debian",
                    "emp_client_linux_distroID": "1827",
                    "emp_staff_number": "40926",
                    "emp_staff_numberID": "1820",
                    "emp_firstname": "Horst-Dieter",
                    "emp_firstnameID": "1821",
                    "emp_lastname": "Berg",
                    "emp_lastnameID": "1822",
                    "emp_email_address": "horst-dieter.berg@example.com",
                    "emp_email_addressID": "1823",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "227",
                    "ci_project_ids": "413,414",
                    "emp_ad_username": "elsbeth.thiele",
                    "emp_ad_usernameID": "1690",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "1688",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Ubuntu",
                    "emp_client_linux_distroID": "1691",
                    "emp_staff_number": "19077",
                    "emp_staff_numberID": "1684",
                    "emp_firstname": "Elsbeth",
                    "emp_firstnameID": "1685",
                    "emp_lastname": "Thiele",
                    "emp_lastnameID": "1686",
                    "emp_email_address": "elsbeth.thiele@example.com",
                    "emp_email_addressID": "1687",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "224",
                    "ci_project_ids": "407,408",
                    "emp_ad_username": "beatrix.hamann",
                    "emp_ad_usernameID": "1666",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "1664",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Manjaro",
                    "emp_client_linux_distroID": "1667",
                    "emp_staff_number": "48416",
                    "emp_staff_numberID": "1660",
                    "emp_firstname": "Beatrix",
                    "emp_firstnameID": "1661",
                    "emp_lastname": "Hamann",
                    "emp_lastnameID": "1662",
                    "emp_email_address": "beatrix.hamann@example.com",
                    "emp_email_addressID": "1663",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "218",
                    "ci_project_ids": "395,396",
                    "emp_ad_username": "renata.bock",
                    "emp_ad_usernameID": "1618",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "1616",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Debian",
                    "emp_client_linux_distroID": "1619",
                    "emp_staff_number": "71878",
                    "emp_staff_numberID": "1612",
                    "emp_firstname": "Renata",
                    "emp_firstnameID": "1613",
                    "emp_lastname": "Bock",
                    "emp_lastnameID": "1614",
                    "emp_email_address": "renata.bock@example.com",
                    "emp_email_addressID": "1615",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "212",
                    "ci_project_ids": "383,384",
                    "emp_ad_username": "hans-heinrich.gerlach",
                    "emp_ad_usernameID": "1570",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "1568",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Ubuntu",
                    "emp_client_linux_distroID": "1571",
                    "emp_staff_number": "46920",
                    "emp_staff_numberID": "1564",
                    "emp_firstname": "Hans-Heinrich",
                    "emp_firstnameID": "1565",
                    "emp_lastname": "Gerlach",
                    "emp_lastnameID": "1566",
                    "emp_email_address": "hans-heinrich.gerlach@example.com",
                    "emp_email_addressID": "1567",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "194",
                    "ci_project_ids": "347,348",
                    "emp_ad_username": "regine.rausch",
                    "emp_ad_usernameID": "1426",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "1424",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "ArchLinux",
                    "emp_client_linux_distroID": "1427",
                    "emp_staff_number": "25895",
                    "emp_staff_numberID": "1420",
                    "emp_firstname": "Regine",
                    "emp_firstnameID": "1421",
                    "emp_lastname": "Rausch",
                    "emp_lastnameID": "1422",
                    "emp_email_address": "regine.rausch@example.com",
                    "emp_email_addressID": "1423",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "168",
                    "ci_project_ids": "295,296",
                    "emp_ad_username": "adelheid.bruns",
                    "emp_ad_usernameID": "1218",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "1216",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "ArchLinux",
                    "emp_client_linux_distroID": "1219",
                    "emp_staff_number": "26578",
                    "emp_staff_numberID": "1212",
                    "emp_firstname": "Adelheid",
                    "emp_firstnameID": "1213",
                    "emp_lastname": "Bruns",
                    "emp_lastnameID": "1214",
                    "emp_email_address": "adelheid.bruns@example.com",
                    "emp_email_addressID": "1215",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "167",
                    "ci_project_ids": "293,294",
                    "emp_ad_username": "gunda.eberhardt",
                    "emp_ad_usernameID": "1210",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "1208",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Ubuntu",
                    "emp_client_linux_distroID": "1211",
                    "emp_staff_number": "65586",
                    "emp_staff_numberID": "1204",
                    "emp_firstname": "Gunda",
                    "emp_firstnameID": "1205",
                    "emp_lastname": "Eberhardt",
                    "emp_lastnameID": "1206",
                    "emp_email_address": "gunda.eberhardt@example.com",
                    "emp_email_addressID": "1207",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "163",
                    "ci_project_ids": "285,286",
                    "emp_ad_username": "albin.hohmann",
                    "emp_ad_usernameID": "1178",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "1176",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Debian",
                    "emp_client_linux_distroID": "1179",
                    "emp_staff_number": "25838",
                    "emp_staff_numberID": "1172",
                    "emp_firstname": "Albin",
                    "emp_firstnameID": "1173",
                    "emp_lastname": "Hohmann",
                    "emp_lastnameID": "1174",
                    "emp_email_address": "albin.hohmann@example.com",
                    "emp_email_addressID": "1175",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "160",
                    "ci_project_ids": "279,280",
                    "emp_ad_username": "hubert.voigt",
                    "emp_ad_usernameID": "1154",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "1152",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "ArchLinux",
                    "emp_client_linux_distroID": "1155",
                    "emp_staff_number": "13811",
                    "emp_staff_numberID": "1148",
                    "emp_firstname": "Hubert",
                    "emp_firstnameID": "1149",
                    "emp_lastname": "Voigt",
                    "emp_lastnameID": "1150",
                    "emp_email_address": "hubert.voigt@example.com",
                    "emp_email_addressID": "1151",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "158",
                    "ci_project_ids": "275,276",
                    "emp_ad_username": "inge.barthel",
                    "emp_ad_usernameID": "1138",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "1136",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Debian",
                    "emp_client_linux_distroID": "1139",
                    "emp_staff_number": "29409",
                    "emp_staff_numberID": "1132",
                    "emp_firstname": "Inge",
                    "emp_firstnameID": "1133",
                    "emp_lastname": "Barthel",
                    "emp_lastnameID": "1134",
                    "emp_email_address": "inge.barthel@example.com",
                    "emp_email_addressID": "1135",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "150",
                    "ci_project_ids": "259,260",
                    "emp_ad_username": "bruno.thiel",
                    "emp_ad_usernameID": "1074",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "1072",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "ArchLinux",
                    "emp_client_linux_distroID": "1075",
                    "emp_staff_number": "87049",
                    "emp_staff_numberID": "1068",
                    "emp_firstname": "Bruno",
                    "emp_firstnameID": "1069",
                    "emp_lastname": "Thiel",
                    "emp_lastnameID": "1070",
                    "emp_email_address": "bruno.thiel@example.com",
                    "emp_email_addressID": "1071",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "144",
                    "ci_project_ids": "247,248",
                    "emp_ad_username": "miriam.schott",
                    "emp_ad_usernameID": "1026",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "1024",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Debian",
                    "emp_client_linux_distroID": "1027",
                    "emp_staff_number": "52084",
                    "emp_staff_numberID": "1020",
                    "emp_firstname": "Miriam",
                    "emp_firstnameID": "1021",
                    "emp_lastname": "Schott",
                    "emp_lastnameID": "1022",
                    "emp_email_address": "miriam.schott@example.com",
                    "emp_email_addressID": "1023",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "143",
                    "ci_project_ids": "245,246",
                    "emp_ad_username": "andrzej.sch&uuml;tz",
                    "emp_ad_usernameID": "1018",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "1016",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Linux Mint",
                    "emp_client_linux_distroID": "1019",
                    "emp_staff_number": "35380",
                    "emp_staff_numberID": "1012",
                    "emp_firstname": "Andrzej",
                    "emp_firstnameID": "1013",
                    "emp_lastname": "Sch&uuml;tz",
                    "emp_lastnameID": "1014",
                    "emp_email_address": "andrzej.sch&uuml;tz@example.com",
                    "emp_email_addressID": "1015",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "142",
                    "ci_project_ids": "243,244",
                    "emp_ad_username": "ronny.witte",
                    "emp_ad_usernameID": "1010",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "1008",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Manjaro",
                    "emp_client_linux_distroID": "1011",
                    "emp_staff_number": "22179",
                    "emp_staff_numberID": "1004",
                    "emp_firstname": "Ronny",
                    "emp_firstnameID": "1005",
                    "emp_lastname": "Witte",
                    "emp_lastnameID": "1006",
                    "emp_email_address": "ronny.witte@example.com",
                    "emp_email_addressID": "1007",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "133",
                    "ci_project_ids": "225,226",
                    "emp_ad_username": "werner.engelhardt",
                    "emp_ad_usernameID": "938",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "936",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Manjaro",
                    "emp_client_linux_distroID": "939",
                    "emp_staff_number": "3827",
                    "emp_staff_numberID": "932",
                    "emp_firstname": "Werner",
                    "emp_firstnameID": "933",
                    "emp_lastname": "Engelhardt",
                    "emp_lastnameID": "934",
                    "emp_email_address": "werner.engelhardt@example.com",
                    "emp_email_addressID": "935",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "129",
                    "ci_project_ids": "217,218",
                    "emp_ad_username": "helfried.r&ouml;mer",
                    "emp_ad_usernameID": "906",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "904",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Debian",
                    "emp_client_linux_distroID": "907",
                    "emp_staff_number": "98563",
                    "emp_staff_numberID": "900",
                    "emp_firstname": "Helfried",
                    "emp_firstnameID": "901",
                    "emp_lastname": "R&ouml;mer",
                    "emp_lastnameID": "902",
                    "emp_email_address": "helfried.r&ouml;mer@example.com",
                    "emp_email_addressID": "903",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "125",
                    "ci_project_ids": "209,210",
                    "emp_ad_username": "evelyne.engelmann",
                    "emp_ad_usernameID": "874",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "872",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Debian",
                    "emp_client_linux_distroID": "875",
                    "emp_staff_number": "57743",
                    "emp_staff_numberID": "868",
                    "emp_firstname": "Evelyne",
                    "emp_firstnameID": "869",
                    "emp_lastname": "Engelmann",
                    "emp_lastnameID": "870",
                    "emp_email_address": "evelyne.engelmann@example.com",
                    "emp_email_addressID": "871",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "107",
                    "ci_project_ids": "173,174",
                    "emp_ad_username": "claudia.schott",
                    "emp_ad_usernameID": "730",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "728",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Linux Mint",
                    "emp_client_linux_distroID": "731",
                    "emp_staff_number": "5648",
                    "emp_staff_numberID": "724",
                    "emp_firstname": "Claudia",
                    "emp_firstnameID": "725",
                    "emp_lastname": "Schott",
                    "emp_lastnameID": "726",
                    "emp_email_address": "claudia.schott@example.com",
                    "emp_email_addressID": "727",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "105",
                    "ci_project_ids": "169,170",
                    "emp_ad_username": "margitta.fricke",
                    "emp_ad_usernameID": "714",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "712",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Debian",
                    "emp_client_linux_distroID": "715",
                    "emp_staff_number": "34958",
                    "emp_staff_numberID": "708",
                    "emp_firstname": "Margitta",
                    "emp_firstnameID": "709",
                    "emp_lastname": "Fricke",
                    "emp_lastnameID": "710",
                    "emp_email_address": "margitta.fricke@example.com",
                    "emp_email_addressID": "711",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "87",
                    "ci_project_ids": "133,134",
                    "emp_ad_username": "felix.fritz",
                    "emp_ad_usernameID": "570",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "568",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "ArchLinux",
                    "emp_client_linux_distroID": "571",
                    "emp_staff_number": "86868",
                    "emp_staff_numberID": "564",
                    "emp_firstname": "Felix",
                    "emp_firstnameID": "565",
                    "emp_lastname": "Fritz",
                    "emp_lastnameID": "566",
                    "emp_email_address": "felix.fritz@example.com",
                    "emp_email_addressID": "567",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "86",
                    "ci_project_ids": "131,132",
                    "emp_ad_username": "wanda.franke",
                    "emp_ad_usernameID": "562",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "560",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Ubuntu",
                    "emp_client_linux_distroID": "563",
                    "emp_staff_number": "43612",
                    "emp_staff_numberID": "556",
                    "emp_firstname": "Wanda",
                    "emp_firstnameID": "557",
                    "emp_lastname": "Franke",
                    "emp_lastnameID": "558",
                    "emp_email_address": "wanda.franke@example.com",
                    "emp_email_addressID": "559",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "84",
                    "ci_project_ids": "127,128",
                    "emp_ad_username": "ingolf.frank",
                    "emp_ad_usernameID": "546",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "544",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Manjaro",
                    "emp_client_linux_distroID": "547",
                    "emp_staff_number": "11285",
                    "emp_staff_numberID": "540",
                    "emp_firstname": "Ingolf",
                    "emp_firstnameID": "541",
                    "emp_lastname": "Frank",
                    "emp_lastnameID": "542",
                    "emp_email_address": "ingolf.frank@example.com",
                    "emp_email_addressID": "543",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "78",
                    "ci_project_ids": "115,116",
                    "emp_ad_username": "gudrun.lauer",
                    "emp_ad_usernameID": "498",
                    "emp_client_os_family": "Windows",
                    "emp_client_os_familyID": "496",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "ArchLinux",
                    "emp_client_linux_distroID": "499",
                    "emp_staff_number": "89993",
                    "emp_staff_numberID": "492",
                    "emp_firstname": "Gudrun",
                    "emp_firstnameID": "493",
                    "emp_lastname": "Lauer",
                    "emp_lastnameID": "494",
                    "emp_email_address": "gudrun.lauer@example.com",
                    "emp_email_addressID": "495",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "62",
                    "ci_project_ids": "83,84",
                    "emp_ad_username": "adele.hirsch",
                    "emp_ad_usernameID": "370",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "368",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Linux Mint",
                    "emp_client_linux_distroID": "371",
                    "emp_staff_number": "39969",
                    "emp_staff_numberID": "364",
                    "emp_firstname": "Adele",
                    "emp_firstnameID": "365",
                    "emp_lastname": "Hirsch",
                    "emp_lastnameID": "366",
                    "emp_email_address": "adele.hirsch@example.com",
                    "emp_email_addressID": "367",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "59",
                    "ci_project_ids": "77,78",
                    "emp_ad_username": "alma.nowak",
                    "emp_ad_usernameID": "346",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "344",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Linux Mint",
                    "emp_client_linux_distroID": "347",
                    "emp_staff_number": "77901",
                    "emp_staff_numberID": "340",
                    "emp_firstname": "Alma",
                    "emp_firstnameID": "341",
                    "emp_lastname": "Nowak",
                    "emp_lastnameID": "342",
                    "emp_email_address": "alma.nowak@example.com",
                    "emp_email_addressID": "343",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "52",
                    "ci_project_ids": "63,64",
                    "emp_ad_username": "rolf-dieter.bartsch",
                    "emp_ad_usernameID": "290",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "288",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Debian",
                    "emp_client_linux_distroID": "291",
                    "emp_staff_number": "16761",
                    "emp_staff_numberID": "284",
                    "emp_firstname": "Rolf-Dieter",
                    "emp_firstnameID": "285",
                    "emp_lastname": "Bartsch",
                    "emp_lastnameID": "286",
                    "emp_email_address": "rolf-dieter.bartsch@example.com",
                    "emp_email_addressID": "287",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                },
                {
                    "id": "40",
                    "ci_project_ids": "40",
                    "emp_ad_username": "max.mustermann",
                    "emp_ad_usernameID": "192",
                    "emp_client_os_family": "Linux",
                    "emp_client_os_familyID": "193",
                    "emp_client_win_version": "",
                    "emp_client_win_versionID": "",
                    "emp_client_linux_distro": "Ubuntu",
                    "emp_client_linux_distroID": "194",
                    "emp_staff_number": "5002",
                    "emp_staff_numberID": "188",
                    "emp_firstname": "Max",
                    "emp_firstnameID": "189",
                    "emp_lastname": "Mustermann",
                    "emp_lastnameID": "190",
                    "emp_email_address": "max.mustermann@example.com",
                    "emp_email_addressID": "191",
                    "color": null,
                    "ci_type_id": "12",
                    "ci_type_name": "emp_germany_berlin"
                }
            ]
        }
    }
}`,
	})

	type args struct {
		ciTypeID int
		out      interface{}
	}

	type EmployeeReturn struct {
		Data struct {
			Data struct {
				AttributeList map[int]struct {
					AttributeGroupID    string      `json:"attribute_group_id"`
					AttributeTypeID     string      `json:"attribute_type_id"`
					Column              string      `json:"column"`
					Description         string      `json:"description"`
					DisplayStyle        interface{} `json:"display_style"`
					Hint                string      `json:"hint"`
					Historicize         string      `json:"historicize"`
					ID                  string      `json:"id"`
					InputMaxlength      interface{} `json:"input_maxlength"`
					IsActive            string      `json:"is_active"`
					IsAutocomplete      string      `json:"is_autocomplete"`
					IsBold              string      `json:"is_bold"`
					IsEvent             string      `json:"is_event"`
					IsMultiselect       string      `json:"is_multiselect"`
					IsNumeric           string      `json:"is_numeric"`
					IsProjectRestricted string      `json:"is_project_restricted"`
					IsUnique            string      `json:"is_unique"`
					IsUniqueCheck       string      `json:"is_unique_check"`
					Name                string      `json:"name"`
					Note                string      `json:"note"`
					OrderNumber         string      `json:"order_number"`
					Regex               interface{} `json:"regex"`
					ScriptName          interface{} `json:"script_name"`
					Tag                 string      `json:"tag"`
					TextareaCols        interface{} `json:"textarea_cols"`
					TextareaRows        interface{} `json:"textarea_rows"`
					UserID              string      `json:"user_id"`
					ValidFrom           string      `json:"valid_from"`
					Width               interface{} `json:"width"`
					WorkflowID          interface{} `json:"workflow_id"`
				} `json:"attributeList"`
				Breadcrumbs []struct {
					CreateButtonDescription interface{} `json:"create_button_description"`
					CrumbType               string      `json:"crumbType"`
					DefaultAttributeID      string      `json:"default_attribute_id"`
					DefaultProjectID        string      `json:"default_project_id"`
					DefaultSortAttributeID  string      `json:"default_sort_attribute_id"`
					Description             string      `json:"description"`
					Icon                    interface{} `json:"icon"`
					ID                      string      `json:"id"`
					IsActive                string      `json:"is_active"`
					IsAttributeAttach       string      `json:"is_attribute_attach"`
					IsCiAttach              string      `json:"is_ci_attach"`
					IsDefaultSortAsc        string      `json:"is_default_sort_asc"`
					IsEventEnabled          string      `json:"is_event_enabled"`
					IsTabEnabled            string      `json:"is_tab_enabled"`
					Name                    string      `json:"name"`
					Note                    string      `json:"note"`
					OrderNumber             string      `json:"order_number"`
					ParentCiTypeID          string      `json:"parent_ci_type_id"`
					Query                   interface{} `json:"query"`
					Tag                     interface{} `json:"tag"`
					UserID                  string      `json:"user_id"`
					ValidFrom               string      `json:"valid_from"`
				} `json:"breadcrumbs"`
				CiList []struct {
					Color             interface{} `json:"color"`
					EmpEmailAddress   string      `json:"emp_email_address"`
					EmpEmailAddressID string      `json:"emp_email_addressID"`
					EmpFirstname      string      `json:"emp_firstname"`
					EmpFirstnameID    string      `json:"emp_firstnameID"`
					EmpLastname       string      `json:"emp_lastname"`
					EmpLastnameID     string      `json:"emp_lastnameID"`
					EmpStaffNumber    string      `json:"emp_staff_number"`
					EmpStaffNumberID  string      `json:"emp_staff_numberID"`
					ID                string      `json:"id"`
				} `json:"ciList"`
				CiTypeAttach            string      `json:"ciTypeAttach"`
				CreateButtonDescription interface{} `json:"createButtonDescription"`
				DefaultOrderBy          interface{} `json:"defaultOrderBy"`
				IsQuery                 bool        `json:"isQuery"`
				ListEdit                string      `json:"listEdit"`
				Paginator               struct{}    `json:"paginator"`
				Scrollbar               bool        `json:"scrollbar"`
				TypeName                string      `json:"typeName"`
			} `json:"data"`
		} `json:"data"`
		Message string `json:"message"`
		Success bool   `json:"success"`
	}
	var citypetest1 EmployeeReturn

	tests := []struct {
		name    string
		Config  Config
		args    args
		wantErr bool
	}{
		{
			"query citype 1",
			Config{},
			args{12, citypetest1},
			false,
		},
		{
			"fail query citype -1",
			Config{},
			args{-1, citypetest1},
			true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			c := New()
			e := c.LoadConfig(configFile)
			if e != nil {
				t.Fatal(e)
			}

			if err := c.Login(); err != nil {
				t.Fatalf("Login failed: %v\n", err)
			}

			var citypetest2 EmployeeReturn
			if err := c.CiListByCiTypeID(tt.args.ciTypeID, &citypetest2); (err != nil) != tt.wantErr {
				t.Fatalf("Cmdb.CiListByCiTypeID() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}
