package infocmdb

import (
	"encoding/json"
	"reflect"
	"testing"
)

func TestUnmarshalWorkflowContext(t *testing.T) {
	tests := []struct {
		name    string
		ctxData string
		wantCtx *WorkflowContext
		wantErr bool
	}{
		{
			name:    "ci_create github repository",
			ctxData: `{"Environment":{"APPLICATION_ENV":"development","APPLICATION_PATH":"\/app\/application","APPLICATION_URL":"http:\/\/infocmdb.local\/","APPLICATION_DATA":"\/app\/data","APPLICATION_PUBLIC":"\/app\/public\/","WORKFLOW_CONFIG_PATH":"\/app\/data\/configs\/workflows","WORKFLOW_DEBUGGING":"false"},"ciid":8,"triggerType":"ci_create","data":{"new":{"relations":[],"projects":{"1":{"id":"1","name":"General","description":"General","note":"General","order_number":"10","is_active":"1","user_id":"1","valid_from":"2019-11-27 15:53:32","ci_project_valid_from":"2019-11-28 12:23:27","ci_project_history_id":"33"}},"ciTypeId":"3","ciTypeName":"res_github_repo","attributes":{"1":{"6":{"id":"1","name":"res_github_repo_name","description":"Name","note":"","hint":"","attribute_type_id":"1","attribute_group_id":"2","order_number":"20","column":"1","is_unique":"0","is_numeric":"0","is_bold":"0","is_event":"0","is_unique_check":"0","is_autocomplete":"0","is_multiselect":"0","is_project_restricted":"0","regex":"","workflow_id":null,"script_name":null,"tag":"","input_maxlength":"0","textarea_cols":"30","textarea_rows":"3","is_active":"1","user_id":"1","valid_from":"2019-11-28 12:23:27","historicize":"1","display_style":null,"attributeTypeName":"input","attribute_group":"Resource Information","parent_attribute_group":"0","value_text":"demo","value_date":null,"value_ci":null,"ciAttributeId":"6","initial":"1","valueNote":null,"history_id":"32","value_default":null}}}}},"user_id":"1"}`,
			wantCtx: &WorkflowContext{
				Environment: map[string]string{
					"APPLICATION_ENV":      "development",
					"APPLICATION_PATH":     "/app/application",
					"APPLICATION_URL":      "http://infocmdb.local/",
					"APPLICATION_DATA":     "/app/data",
					"APPLICATION_PUBLIC":   "/app/public/",
					"WORKFLOW_CONFIG_PATH": "/app/data/configs/workflows",
					"WORKFLOW_DEBUGGING":   "false",
				},
				Ciid:        8,
				TriggerType: "ci_create",
				Data: Data{
					New: &CiDetail{
						Relations: []Relation{},
						Projects: map[int]Project{
							1: {
								ID:                 "1",
								Name:               "General",
								Description:        "General",
								Note:               "General",
								OrderNumber:        "10",
								IsActive:           "1",
								UserID:             "1",
								ValidFrom:          "2019-11-27 15:53:32",
								CiProjectValidFrom: "2019-11-28 12:23:27",
								CiProjectHistoryID: "33",
							},
						},
						CiTypeID:   "3",
						CiTypeName: "res_github_repo",
						Attributes: map[int]map[int]Attribute{
							1: {
								6: Attribute{
									ID:                   "1",
									Name:                 "res_github_repo_name",
									Description:          "Name",
									Note:                 "",
									Hint:                 "",
									AttributeTypeID:      "1",
									AttributeGroupID:     "2",
									OrderNumber:          "20",
									Column:               "1",
									IsUnique:             "0",
									IsNumeric:            "0",
									IsBold:               "0",
									IsEvent:              "0",
									IsUniqueCheck:        "0",
									IsAutocomplete:       "0",
									IsMultiselect:        "0",
									IsProjectRestricted:  "0",
									Regex:                "",
									WorkflowID:           0,
									ScriptName:           "",
									Tag:                  "",
									InputMaxlength:       "0",
									TextareaCols:         "30",
									TextareaRows:         "3",
									IsActive:             "1",
									UserID:               "1",
									ValidFrom:            "2019-11-28 12:23:27",
									Historicize:          "1",
									DisplayStyle:         "",
									AttributeTypeName:    "input",
									AttributeGroup:       "Resource Information",
									ParentAttributeGroup: "0",
									ValueText:            "demo",
									ValueDate:            "",
									ValueCi:              "",
									CiAttributeID:        "6",
									Initial:              "1",
									ValueNote:            "",
									HistoryID:            "32",
									ValueDefault:         "",
								},
							},
						},
					},
				},
				UserID: "1",
			},
			wantErr: false,
		},
		{
			name:    "ci_create jira issue",
			ctxData: `{"Environment":{"APPLICATION_ENV":"development","APPLICATION_PATH":"/app/application","APPLICATION_URL":"http://infocmdb.local/","APPLICATION_DATA":"/app/data","APPLICATION_PUBLIC":"/app/public/","WORKFLOW_CONFIG_PATH":"/app/data/configs/workflows","WORKFLOW_DEBUGGING":"false"},"ciid":21,"triggerType":"ci_create","data":{"new":{"relations":[],"projects":{"1":{"id":"1","name":"General","description":"General","note":"General","order_number":"10","is_active":"1","user_id":"1","valid_from":"2019-11-27 15:53:32","ci_project_valid_from":"2019-12-02 10:30:17","ci_project_history_id":"78"}},"ciTypeId":"6","ciTypeName":"res_jira_issue","attributes":{"5":{"32":{"id":"5","name":"res_jira_issue_summary","description":"Zusammenfassung","note":"JIRA Issue Zusammenfassung","hint":"","attribute_type_id":"1","attribute_group_id":"2","order_number":"50","column":"1","is_unique":"0","is_numeric":"0","is_bold":"0","is_event":"0","is_unique_check":"0","is_autocomplete":"0","is_multiselect":"0","is_project_restricted":"0","regex":"","workflow_id":null,"script_name":null,"tag":"","input_maxlength":"0","textarea_cols":"30","textarea_rows":"3","is_active":"1","user_id":"1","valid_from":"2019-12-02 10:30:17","historicize":"1","display_style":null,"attributeTypeName":"input","attribute_group":"Resource Information","parent_attribute_group":"0","value_text":"Demo","value_date":null,"value_ci":null,"ciAttributeId":"32","initial":"1","valueNote":null,"history_id":"77","value_default":null}},"6":{"30":{"id":"6","name":"res_jira_issue_project_key","description":"Projekt","note":"JIRA Issue Projekt Key","hint":"","attribute_type_id":"21","attribute_group_id":"2","order_number":"20","column":"1","is_unique":"0","is_numeric":"0","is_bold":"0","is_event":"0","is_unique_check":"0","is_autocomplete":"1","is_multiselect":"0","is_project_restricted":"0","regex":null,"workflow_id":null,"script_name":null,"tag":"","input_maxlength":null,"textarea_cols":"180","textarea_rows":null,"is_active":"1","user_id":"1","valid_from":"2019-12-02 10:30:17","historicize":"1","display_style":"optionList","attributeTypeName":"selectQuery","attribute_group":"Resource Information","parent_attribute_group":"0","value_text":null,"value_date":null,"value_ci":"11","ciAttributeId":"30","initial":"1","valueNote":null,"history_id":"77","value_default":null}},"8":{"31":{"id":"8","name":"res_jira_issue_issuetype_name","description":"Typ","note":"JIRA Issue Typ Name","hint":"","attribute_type_id":"16","attribute_group_id":"2","order_number":"30","column":"1","is_unique":"0","is_numeric":"0","is_bold":"0","is_event":"0","is_unique_check":"0","is_autocomplete":"1","is_multiselect":"0","is_project_restricted":"0","regex":null,"workflow_id":null,"script_name":null,"tag":"","input_maxlength":null,"textarea_cols":"180","textarea_rows":null,"is_active":"1","user_id":"1","valid_from":"2019-12-02 10:30:17","historicize":"1","display_style":null,"attributeTypeName":"ciType","attribute_group":"Resource Information","parent_attribute_group":"0","value_text":null,"value_date":null,"value_ci":"13","ciAttributeId":"31","initial":"1","valueNote":null,"history_id":"77","value_default":null}}}}},"user_id":"1"}`,
			wantCtx: &WorkflowContext{
				Environment: map[string]string{
					"APPLICATION_ENV":      "development",
					"APPLICATION_PATH":     "/app/application",
					"APPLICATION_URL":      "http://infocmdb.local/",
					"APPLICATION_DATA":     "/app/data",
					"APPLICATION_PUBLIC":   "/app/public/",
					"WORKFLOW_CONFIG_PATH": "/app/data/configs/workflows",
					"WORKFLOW_DEBUGGING":   "false",
				},
				Ciid:        21,
				TriggerType: "ci_create",
				Data: Data{
					New: &CiDetail{
						Relations: []Relation{},
						Projects: map[int]Project{
							1: {
								ID:                 "1",
								Name:               "General",
								Description:        "General",
								Note:               "General",
								OrderNumber:        "10",
								IsActive:           "1",
								UserID:             "1",
								ValidFrom:          "2019-11-27 15:53:32",
								CiProjectValidFrom: "2019-12-02 10:30:17",
								CiProjectHistoryID: "78",
							},
						},
						CiTypeID:   "6",
						CiTypeName: "res_jira_issue",
						Attributes: map[int]map[int]Attribute{
							6: {
								30: Attribute{
									ID:                   "6",
									Name:                 "res_jira_issue_project_key",
									Description:          "Projekt",
									Note:                 "JIRA Issue Projekt Key",
									Hint:                 "",
									AttributeTypeID:      "21",
									AttributeGroupID:     "2",
									OrderNumber:          "20",
									Column:               "1",
									IsUnique:             "0",
									IsNumeric:            "0",
									IsBold:               "0",
									IsEvent:              "0",
									IsUniqueCheck:        "0",
									IsAutocomplete:       "1",
									IsMultiselect:        "0",
									IsProjectRestricted:  "0",
									Regex:                "",
									WorkflowID:           0,
									ScriptName:           "",
									Tag:                  "",
									InputMaxlength:       "",
									TextareaCols:         "180",
									TextareaRows:         "",
									IsActive:             "1",
									UserID:               "1",
									ValidFrom:            "2019-12-02 10:30:17",
									Historicize:          "1",
									DisplayStyle:         "optionList",
									AttributeTypeName:    "selectQuery",
									AttributeGroup:       "Resource Information",
									ParentAttributeGroup: "0",
									ValueText:            "",
									ValueDate:            "",
									ValueCi:              "11",
									CiAttributeID:        "30",
									Initial:              "1",
									ValueNote:            "",
									HistoryID:            "77",
									ValueDefault:         "",
								},
							},
							8: {
								31: Attribute{
									ID:                   "8",
									Name:                 "res_jira_issue_issuetype_name",
									Description:          "Typ",
									Note:                 "JIRA Issue Typ Name",
									Hint:                 "",
									AttributeTypeID:      "16",
									AttributeGroupID:     "2",
									OrderNumber:          "30",
									Column:               "1",
									IsUnique:             "0",
									IsNumeric:            "0",
									IsBold:               "0",
									IsEvent:              "0",
									IsUniqueCheck:        "0",
									IsAutocomplete:       "1",
									IsMultiselect:        "0",
									IsProjectRestricted:  "0",
									Regex:                "",
									WorkflowID:           0,
									ScriptName:           "",
									Tag:                  "",
									InputMaxlength:       "",
									TextareaCols:         "180",
									TextareaRows:         "",
									IsActive:             "1",
									UserID:               "1",
									ValidFrom:            "2019-12-02 10:30:17",
									Historicize:          "1",
									DisplayStyle:         "",
									AttributeTypeName:    "ciType",
									AttributeGroup:       "Resource Information",
									ParentAttributeGroup: "0",
									ValueText:            "",
									ValueDate:            "",
									ValueCi:              "13",
									CiAttributeID:        "31",
									Initial:              "1",
									ValueNote:            "",
									HistoryID:            "77",
									ValueDefault:         "",
								},
							},
							5: {
								32: Attribute{
									ID:                   "5",
									Name:                 "res_jira_issue_summary",
									Description:          "Zusammenfassung",
									Note:                 "JIRA Issue Zusammenfassung",
									Hint:                 "",
									AttributeTypeID:      "1",
									AttributeGroupID:     "2",
									OrderNumber:          "50",
									Column:               "1",
									IsUnique:             "0",
									IsNumeric:            "0",
									IsBold:               "0",
									IsEvent:              "0",
									IsUniqueCheck:        "0",
									IsAutocomplete:       "0",
									IsMultiselect:        "0",
									IsProjectRestricted:  "0",
									Regex:                "",
									WorkflowID:           0,
									ScriptName:           "",
									Tag:                  "",
									InputMaxlength:       "0",
									TextareaCols:         "30",
									TextareaRows:         "3",
									IsActive:             "1",
									UserID:               "1",
									ValidFrom:            "2019-12-02 10:30:17",
									Historicize:          "1",
									DisplayStyle:         "",
									AttributeTypeName:    "input",
									AttributeGroup:       "Resource Information",
									ParentAttributeGroup: "0",
									ValueText:            "Demo",
									ValueDate:            "",
									ValueCi:              "",
									CiAttributeID:        "32",
									Initial:              "1",
									ValueNote:            "",
									HistoryID:            "77",
									ValueDefault:         "",
								},
							},
						},
					},
				},
				UserID: "1",
			},
			wantErr: false,
		},
		{
			name:    "ci_update github repository",
			ctxData: `{"Environment":{"APPLICATION_ENV":"development","APPLICATION_PATH":"\/app\/application","APPLICATION_URL":"http:\/\/infocmdb.local\/","APPLICATION_DATA":"\/app\/data","APPLICATION_PUBLIC":"\/app\/public\/","WORKFLOW_CONFIG_PATH":"\/app\/data\/configs\/workflows","WORKFLOW_DEBUGGING":"false"},"ciid":3,"triggerType":"ci_update","data":{"old":{"relations":[],"projects":{"1":{"id":"1","name":"General","description":"General","note":"General","order_number":"10","is_active":"1","user_id":"1","valid_from":"2019-11-27 15:53:32","ci_project_valid_from":"2019-11-27 16:43:14","ci_project_history_id":"6"}},"ciTypeId":"3","ciTypeName":"res_github_repo","attributes":{"1":{"1":{"id":"1","name":"res_github_repo_name","description":"Name","note":"","hint":"","attribute_type_id":"1","attribute_group_id":"2","order_number":"20","column":"1","is_unique":"0","is_numeric":"0","is_bold":"0","is_event":"0","is_unique_check":"0","is_autocomplete":"0","is_multiselect":"0","is_project_restricted":"0","regex":"","workflow_id":null,"script_name":null,"tag":"","input_maxlength":"0","textarea_cols":"30","textarea_rows":"3","is_active":"1","user_id":"1","valid_from":"2019-11-28 09:04:31","historicize":"1","display_style":null,"attributeTypeName":"input","attribute_group":"Resource Information","parent_attribute_group":"0","value_text":"demo2","value_date":null,"value_ci":null,"ciAttributeId":"1","initial":"1","valueNote":null,"history_id":"7","value_default":null}}}},"new":{"relations":[],"projects":{"1":{"id":"1","name":"General","description":"General","note":"General","order_number":"10","is_active":"1","user_id":"1","valid_from":"2019-11-27 15:53:32","ci_project_valid_from":"2019-11-27 16:43:14","ci_project_history_id":"6"}},"ciTypeId":"3","ciTypeName":"res_github_repo","attributes":{"1":{"1":{"id":"1","name":"res_github_repo_name","description":"Name","note":"","hint":"","attribute_type_id":"1","attribute_group_id":"2","order_number":"20","column":"1","is_unique":"0","is_numeric":"0","is_bold":"0","is_event":"0","is_unique_check":"0","is_autocomplete":"0","is_multiselect":"0","is_project_restricted":"0","regex":"","workflow_id":null,"script_name":null,"tag":"","input_maxlength":"0","textarea_cols":"30","textarea_rows":"3","is_active":"1","user_id":"1","valid_from":"2019-11-28 09:58:07","historicize":"1","display_style":null,"attributeTypeName":"input","attribute_group":"Resource Information","parent_attribute_group":"0","value_text":"demo","value_date":null,"value_ci":null,"ciAttributeId":"1","initial":"1","valueNote":null,"history_id":"8","value_default":null}}}}},"user_id":"1"}`,
			wantCtx: &WorkflowContext{
				Environment: map[string]string{
					"APPLICATION_ENV":      "development",
					"APPLICATION_PATH":     "/app/application",
					"APPLICATION_URL":      "http://infocmdb.local/",
					"APPLICATION_DATA":     "/app/data",
					"APPLICATION_PUBLIC":   "/app/public/",
					"WORKFLOW_CONFIG_PATH": "/app/data/configs/workflows",
					"WORKFLOW_DEBUGGING":   "false",
				},
				Ciid:        3,
				TriggerType: "ci_update",
				Data: Data{
					Old: &CiDetail{
						Relations: []Relation{},
						Projects: map[int]Project{
							1: {
								ID:                 "1",
								Name:               "General",
								Description:        "General",
								Note:               "General",
								OrderNumber:        "10",
								IsActive:           "1",
								UserID:             "1",
								ValidFrom:          "2019-11-27 15:53:32",
								CiProjectValidFrom: "2019-11-27 16:43:14",
								CiProjectHistoryID: "6",
							},
						},
						CiTypeID:   "3",
						CiTypeName: "res_github_repo",
						Attributes: map[int]map[int]Attribute{
							1: {
								1: Attribute{
									ID:                   "1",
									Name:                 "res_github_repo_name",
									Description:          "Name",
									Note:                 "",
									Hint:                 "",
									AttributeTypeID:      "1",
									AttributeGroupID:     "2",
									OrderNumber:          "20",
									Column:               "1",
									IsUnique:             "0",
									IsNumeric:            "0",
									IsBold:               "0",
									IsEvent:              "0",
									IsUniqueCheck:        "0",
									IsAutocomplete:       "0",
									IsMultiselect:        "0",
									IsProjectRestricted:  "0",
									Regex:                "",
									WorkflowID:           0,
									ScriptName:           "",
									Tag:                  "",
									InputMaxlength:       "0",
									TextareaCols:         "30",
									TextareaRows:         "3",
									IsActive:             "1",
									UserID:               "1",
									ValidFrom:            "2019-11-28 09:04:31",
									Historicize:          "1",
									DisplayStyle:         "",
									AttributeTypeName:    "input",
									AttributeGroup:       "Resource Information",
									ParentAttributeGroup: "0",
									ValueText:            "demo2",
									ValueDate:            "",
									ValueCi:              "",
									CiAttributeID:        "1",
									Initial:              "1",
									ValueNote:            "",
									HistoryID:            "7",
									ValueDefault:         "",
								},
							},
						},
					},
					New: &CiDetail{
						Relations: []Relation{},
						Projects: map[int]Project{
							1: {
								ID:                 "1",
								Name:               "General",
								Description:        "General",
								Note:               "General",
								OrderNumber:        "10",
								IsActive:           "1",
								UserID:             "1",
								ValidFrom:          "2019-11-27 15:53:32",
								CiProjectValidFrom: "2019-11-27 16:43:14",
								CiProjectHistoryID: "6",
							},
						},
						CiTypeID:   "3",
						CiTypeName: "res_github_repo",
						Attributes: map[int]map[int]Attribute{
							1: {
								1: Attribute{
									ID:                   "1",
									Name:                 "res_github_repo_name",
									Description:          "Name",
									Note:                 "",
									Hint:                 "",
									AttributeTypeID:      "1",
									AttributeGroupID:     "2",
									OrderNumber:          "20",
									Column:               "1",
									IsUnique:             "0",
									IsNumeric:            "0",
									IsBold:               "0",
									IsEvent:              "0",
									IsUniqueCheck:        "0",
									IsAutocomplete:       "0",
									IsMultiselect:        "0",
									IsProjectRestricted:  "0",
									Regex:                "",
									WorkflowID:           0,
									ScriptName:           "",
									Tag:                  "",
									InputMaxlength:       "0",
									TextareaCols:         "30",
									TextareaRows:         "3",
									IsActive:             "1",
									UserID:               "1",
									ValidFrom:            "2019-11-28 09:58:07",
									Historicize:          "1",
									DisplayStyle:         "",
									AttributeTypeName:    "input",
									AttributeGroup:       "Resource Information",
									ParentAttributeGroup: "0",
									ValueText:            "demo",
									ValueDate:            "",
									ValueCi:              "",
									CiAttributeID:        "1",
									Initial:              "1",
									ValueNote:            "",
									HistoryID:            "8",
									ValueDefault:         "",
								},
							},
						},
					},
				},
				UserID: "1",
			},
			wantErr: false,
		},
		{
			name:    "ci_delete github repository",
			ctxData: `{"Environment":{"APPLICATION_ENV":"development","APPLICATION_PATH":"\/app\/application","APPLICATION_URL":"http:\/\/infocmdb.local\/","APPLICATION_DATA":"\/app\/data","APPLICATION_PUBLIC":"\/app\/public\/","WORKFLOW_CONFIG_PATH":"\/app\/data\/configs\/workflows","WORKFLOW_DEBUGGING":"false"},"ciid":3,"triggerType":"ci_delete","data":{"old":{"relations":[],"projects":{"1":{"id":"1","name":"General","description":"General","note":"General","order_number":"10","is_active":"1","user_id":"1","valid_from":"2019-11-27 15:53:32","ci_project_valid_from":"2019-11-27 16:43:14","ci_project_history_id":"6"}},"ciTypeId":"3","ciTypeName":"res_github_repo","attributes":{"1":{"1":{"id":"1","name":"res_github_repo_name","description":"Name","note":"","hint":"","attribute_type_id":"1","attribute_group_id":"2","order_number":"20","column":"1","is_unique":"0","is_numeric":"0","is_bold":"0","is_event":"0","is_unique_check":"0","is_autocomplete":"0","is_multiselect":"0","is_project_restricted":"0","regex":"","workflow_id":null,"script_name":null,"tag":"","input_maxlength":"0","textarea_cols":"30","textarea_rows":"3","is_active":"1","user_id":"1","valid_from":"2019-11-28 09:58:07","historicize":"1","display_style":null,"attributeTypeName":"input","attribute_group":"Resource Information","parent_attribute_group":"0","value_text":"demo","value_date":null,"value_ci":null,"ciAttributeId":"1","initial":"1","valueNote":null,"history_id":"8","value_default":null}}}}},"user_id":"1"}`,
			wantCtx: &WorkflowContext{
				Environment: map[string]string{
					"APPLICATION_ENV":      "development",
					"APPLICATION_PATH":     "/app/application",
					"APPLICATION_URL":      "http://infocmdb.local/",
					"APPLICATION_DATA":     "/app/data",
					"APPLICATION_PUBLIC":   "/app/public/",
					"WORKFLOW_CONFIG_PATH": "/app/data/configs/workflows",
					"WORKFLOW_DEBUGGING":   "false",
				},
				Ciid:        3,
				TriggerType: "ci_delete",
				Data: Data{
					Old: &CiDetail{
						Relations: []Relation{},
						Projects: map[int]Project{
							1: {
								ID:                 "1",
								Name:               "General",
								Description:        "General",
								Note:               "General",
								OrderNumber:        "10",
								IsActive:           "1",
								UserID:             "1",
								ValidFrom:          "2019-11-27 15:53:32",
								CiProjectValidFrom: "2019-11-27 16:43:14",
								CiProjectHistoryID: "6",
							},
						},
						CiTypeID:   "3",
						CiTypeName: "res_github_repo",
						Attributes: map[int]map[int]Attribute{
							1: {
								1: Attribute{
									ID:                   "1",
									Name:                 "res_github_repo_name",
									Description:          "Name",
									Note:                 "",
									Hint:                 "",
									AttributeTypeID:      "1",
									AttributeGroupID:     "2",
									OrderNumber:          "20",
									Column:               "1",
									IsUnique:             "0",
									IsNumeric:            "0",
									IsBold:               "0",
									IsEvent:              "0",
									IsUniqueCheck:        "0",
									IsAutocomplete:       "0",
									IsMultiselect:        "0",
									IsProjectRestricted:  "0",
									Regex:                "",
									WorkflowID:           0,
									ScriptName:           "",
									Tag:                  "",
									InputMaxlength:       "0",
									TextareaCols:         "30",
									TextareaRows:         "3",
									IsActive:             "1",
									UserID:               "1",
									ValidFrom:            "2019-11-28 09:58:07",
									Historicize:          "1",
									DisplayStyle:         "",
									AttributeTypeName:    "input",
									AttributeGroup:       "Resource Information",
									ParentAttributeGroup: "0",
									ValueText:            "demo",
									ValueDate:            "",
									ValueCi:              "",
									CiAttributeID:        "1",
									Initial:              "1",
									ValueNote:            "",
									HistoryID:            "8",
									ValueDefault:         "",
								},
							},
						},
					},
				},
				UserID: "1",
			},
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			gotCtx := new(WorkflowContext)
			err := json.Unmarshal([]byte(tt.ctxData), &gotCtx)
			if (err != nil) != tt.wantErr {
				t.Errorf("json.Unmarshal() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if !reflect.DeepEqual(gotCtx, tt.wantCtx) {
				t.Errorf("json.Unmarshal() gotCtx = %v, wantCtx %v", gotCtx, tt.wantCtx)
			}
		})
	}
}
